### PR TITLE
Updated interface

### PR DESCRIPTION
**Pull request by kelvinxu**
It trains now, but the cost values don't really make sense (the nll is 0.13118 before training commences). Can you try running it when you get a moment?

I also have some code that uses whetlab to automatically optimize the net, if you are interested I can make a seperate pull request for that if this checks out.

### CODE REVIEW

**Comment by bartvm** [comment]
Just started it and I get a validation cost of 1.19. That seems awfully high, it should be around -ln(0.5) = 0.69 I guess... I'll let it run for a few epochs, see what it does.

**Comment by bartvm** [comment]
Actually, it seems okay. After the first epoch it's down to 0.64, and after 3 it goes down to 0.61. That seems to match https://adbrebs.files.wordpress.com/2015/02/nll_pylearn23.jpeg

**Comment by kelvinxu** [comment]
hmm okay, do you have your hd5f file somewhere? Just want to double check to see if that is the issue on my side..

**Comment by bartvm** [comment]
I started transferring it from my home computer, but it will take ~3 hours.

The first image starts with: (74,100,91,74,100,91,73,99,90,72,98,89,70,96,87,69,95,86,68,94,85,68,94,85,74,100,91,75,101,92,75,101,92,75,101,92,74,100...

**Comment by bartvm** [comment]
Oh, by the way, very interested in the Whetlab code, been meaning to look into hyperparameter search for Blocks at one point, and some Whetlab code to play with would be very nice.

**Comment by bartvm** [comment]
It's at `/data/lisatmp3/vanmerb/dogs_vs_cats.hdf5`

**Pull request merged**
